### ISSUE TITLE
Using pre-built libzim libraries causes segmentation fault in pytest

### ISSUE THREAD

**Issue by afreydev** [openzim/libzim#333]
For the [python-libzim](https://github.com/openzim/python-libzim) project,

we are using libzim prebuilt libraries (https://download.openzim.org/release/libzim/libzim_linux-x86_64-6.1.1.tar.gz).

In the github actions test workflow we are getting a **segmentation fault** when it is executing pytest:

![pytest1](https://user-images.githubusercontent.com/43050896/81718248-20112100-9441-11ea-83f6-4a2fcc4299fb.png)

One of the resulting workflows is this: https://github.com/openzim/python-libzim/runs/664923941?check_suite_focus=true

### Error

The most important detail is when we compile **libzim** directly from the source code (in a local env) **pytest** runs well:

```
(python-libzim) vagrant@ubuntu-bionic:~/python-libzim/tests$ pytest .
============================= test session starts ==============================
platform linux -- Python 3.7.5, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/vagrant/python-libzim
collected 3 items                                                              

test_libzim.py ...                                                       [100%]

============================== 3 passed in 0.60s ===============================
```
By using, **pre-built**:
```
collected 3 items                                                                                                                                

tests/test_libzim.py ...                                                                                                                   [100%]

=============================================================== 3 passed in 0.70s ================================================================
Fatal Python error: Segmentation fault

Thread 0x00007fd28abcf740 (most recent call first):
Segmentation fault (core dumped)
```

### python-libzim installation

When the python-libzim installation, we are including libzim headers and dylibs in custom dirs, but we don't have any error and it installs well:

```
creating build/lib.linux-x86_64-3.7
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.7/libzim/libzim.o build/temp.linux-x86_64-3.7/libzim/lib.o -Llib -lzim -o build/lib.linux-x86_64-3.7/libzim.cpython-37m-x86_64-linux-gnu.so
```
```
Obtaining file:///home/vagrant/python-libzim
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: libzim
  Running setup.py develop for libzim
Successfully installed libzim
```

This is a low-level debug screenshot to identify the specific component:

<img width="1208" alt="Screen-Shot-2020-05-07-at-17 15 58-1" src="https://user-images.githubusercontent.com/43050896/81719745-112b6e00-9443-11ea-87db-47eae7605899.png">

We guess, it could exist a bug related to use **pre-built** instead of source code compiled.

**Comment by kelson42** [comment]
@afreydev We have made a new release yesterday https://download.openzim.org/release/libzim/libzim_linux-x86_64-6.1.2.tar.gz

**Comment by mgautierfr** [comment]
Yes. The last release fix a bug really close that the one you describe. This should be fixed with it.

**Comment by afreydev** [comment]
Hello. I have checked upgrading the release and the error persist.

![pytest2](https://user-images.githubusercontent.com/43050896/81743049-a4c26600-9466-11ea-9d09-a43d9a82bd7c.png)

**Comment by mgautierfr** [comment]
I've just test with last libzim release (6.1.4) and branch `pirate-patch-1` of python-libzim (openzim/python-libzim#10) and there is no segmentation fault.

**Comment by kelson42** [comment]
@mgautierfr @rgaudin Clausing this, I guess this is outdated.
